version: '3'
services:
#mssql docker
  student-oglasi-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - studentoglasi2024
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_new
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - studentoglasi2024

  student-oglasi-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=student-oglasi-sql, 1433;Database=200062_200090;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - FIREBASE_TYPE=${FIREBASE_TYPE}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
      - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
      - FIREBASE_AUTH_PROVIDER_CERT_URL=${FIREBASE_AUTH_PROVIDER_CERT_URL}
      - FIREBASE_CLIENT_CERT_URL=${FIREBASE_CLIENT_CERT_URL}
      - FIREBASE_UNIVERSE_DOMAIN=${FIREBASE_UNIVERSE_DOMAIN}
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCESS_KEY=${AZURE_STORAGE_ACCESS_KEY}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - SERVER_ADDRESS=smtp.gmail.com
      - MAIL_SENDER=studentoglasi@gmail.com
      - MAIL_PASS=ocsnmzwxcraeeywi
      - MAIL_PORT=587
    ports:
      - 7198:7198
    networks:
      - studentoglasi2024
    links:
      - student-oglasi-sql
    depends_on:
      - student-oglasi-sql

  student-oglasi-console:
    restart: unless-stopped
    build:
      context: ./StudentOglasi.RabbitMQ
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - SERVER_ADDRESS=smtp.gmail.com
      - MAIL_SENDER=studentoglasi@gmail.com
      - MAIL_PASS=ocsnmzwxcraeeywi
      - MAIL_PORT=587
    networks:
      - studentoglasi2024
    depends_on:
      - rabbitmq
      
networks:
  studentoglasi2024:
    driver: bridge      